### ISSUE TITLE
Equivalent Rx example

### ISSUE THREAD

**Issue by xgrommx** [pandastrike/fairmont-reactive#4]
Hi @dyoder. How can I convert this example to your library?

```js
const {fromEvent} = Rx.Observable;

const inc = fromEvent(incEl, 'click').map(_ => 1);
const dec = fromEvent(decEl, 'click').map(_ => -1);

dec.merge(inc).scan((a, b) => a + b, 0).subscribe(::console.log);

```

**Comment by dyoder** [comment]
Thanks for your question!

We have something roughly equivalent in the [web app counter example][0].

[0]:https://github.com/pandastrike/fairmont-reactive/blob/master/examples/web-apps/counter/src/app.coffee

The closest direct port would look like:

```javascript
const {start, flow, events, map, observe} = FairmontReactive;

var counter = { value: 0 };

start(flow([
  events('click', incEl), 
  map(_ => counter.value++)
]));

start(flow([
  events('click', decEl),
  map(_ => counter.value--)
]));

start(flow([
  events('change', observe(counter)),
  map(::console.log)
]));
```

There's no equivalent at present of `merge` or `scan`. Adding them seems like a reasonable thing to do. If we did that, we could then do something more directly comparable.

```javascript
const {start, flow, events, map, observe} = FairmontReactive;

var counter = { value: 0 };

var inc = start(flow([
  events('click', incEl), 
  map(_ => 1)
]));

var dec = start(flow([
  events('click', decEl),
  map(_ => -1)
]));

start(flow([
  merge inc, dec
  scan (a, b) => a + b, 0
  map(::console.log)
]));
```

**Comment by dyoder** [comment]
We're also considering a function `go` that would get rid of the constant `start(flow([` bits and allowing `flow` to take argument lists as well as arrays. In that case, the last version would become:

```javascript
const {start, flow, events, map, observe, merge, scan} = FairmontReactive;

const inc = flow(
  events('click', incEl), 
  map(_ => 1)
));

const dec = flow(
  events('click', decEl),
  map(_ => -1)
));

go(
  merge inc, dec
  scan (a, b) => a + b, 0
  map(::console.log)
));
```

**Comment by dyoder** [comment]
Made a bunch of minor corrections to the code above.

**Comment by dyoder** [comment]
`merge` is now coded in master as `combine` (because there's already a `merge` in `fairmont-helpers` that does an unrelated thing)

**Comment by dyoder** [comment]
Also coded up `accumulate`.

**Comment by xgrommx** [comment]
@dyoder What is `accumulate`?

**Comment by dyoder** [comment]
@xgrommx `accumulate` is `scan`.

This is implemented and available in Beta 29. There is a bug: see #8.

So the equivalent of your original example is now:

```javascript
var inc = flow(events('click', incEl), map(_ => 1)));

var dec = flow(events('click', decEl), map(_ => -1)));

go(
  combine(inc, dec),
  accumulate((a, b) => a + b, 0),
  map(::console.log)
);
```

Thanks again for your question and for motivating these new additions.

**Comment by xgrommx** [comment]
@dyoder Nice!

**Comment by dyoder** [comment]
@xgrommx that is amazing list. by far the most comprehensive i've seen. thank you!
